### ISSUE TITLE
Front end styling fixes and polish 

### ISSUE THREAD

**Issue by nickzafiropulos** [nearform/initium#18]
I have documented the fixes to the desktop view of the homepage and docs page in Figma (see links against items below).
Please do reach out to me if you would like anything clarifying.

### HOMEPAGE

- [ ]  Top notice bar - Font weight should be Semibold please - [https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566458992](url)
- [ ] Top notice bar - 10px top and bottom padding on this bar please [https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566459754](url)
- [ ] Top notice bar - Close Icon should be smaller here https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566460097
- [ ] Header - The navigation links area should be spaced more left (away from the logos a little) [https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566465611](url)
- [ ] Header - This should be a Hero button https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566460982 
- [ ] Header - Please ensure header has top and bottom padding of 16px https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566468094 
- [ ] Header - logo in header should be bigger and could we please constrain the width of the header so that it matches the main container below (with a little less side padding)? https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566467575
- [ ] Intro block - please check this font style - should be xl medium - https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566468935
- [ ] Intro block - Please check these buttons - they should be primary and secondary xl hero buttons - https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566471294
- [ ] Why initium card - Styling of this card is off - please check the header style and text style https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566472846
- [ ] Roles intro - Please check this font - should be 2xl, font-bold https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566474836
- [ ] Roles intro - Please check this font style and colour - should be base, font-normal, colour token - foreground muted https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566475727
- [ ] USP Block - emoji should be bigger - see design please https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566482487
- [ ] USP Block - This block should have the 'Background subtle' colour token as the background https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566482309
- [ ] USP Block - Once the background has been applied to this block - we may need to check the padding and margin and the corner radius https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566484111
- [ ] USP Block - Please check font style - should be xl, font-normal https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566483266
- [ ] What is Initium block - please check this font style. Should be - 4xl, font-bold https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566486359
- [ ] What is initium block - The whole 'What is initium' block needs a background colour and border - see design. Once this is applied, we will need to match the padding and margin of the design https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566485606
- [ ] What is initium block - please check the styling of these code blocks - in particular the padding and the font style https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566488380
- [ ] What is initium block - there should be some margin set on the code blocks so that the 'and you are done' line is spaced better. https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566489093
- [ ] What is initium block - This should use the Hero (xl primary) button please https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566489934
- [ ] Footer - Footer styling needs a bit of work please - padding and font styles https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:3891&mode=design#566490721

### DOCS PAGE

- [ ] Heading styling - please change to 3xl, font-bold https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566496255
- [ ] Heading styling - Please change to xl, font-bold https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566496595
- [ ] Body text styling - Standard body text should be sm, font-normal https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566497041
- [ ] Side nav styling -Styling of this navigation area doesn't match the design https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566495632
- [ ] Page nav styling - This page navigation doesn't match the design https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566497655 
- [ ] General font styling - Once we have made the updates to the font styling here, we may need to look closer at the padding values around the content elements https://www.figma.com/file/f7KoZcggB50syP0enYrE7Y?node-id=566:4127&mode=design#566498773

### MOBILE

Once we have addressed the above issues, on Desktop, I will be able to review the mobile view and advise on what we need to tweak.

**Comment by pablos4nt0s** [comment]
@nickzafiropulos, let's make sure to include the need to insert the video component on the homepage. We don't have the video yet, but let's get prepared for it.

**Comment by mristic505** [comment]
Just an FYI, I placed both here and in the description the correct repo URL because this issue was reported in a wrong repo. 

https://github.com/nearform/initium-website
